# Generated by Django 5.2.6 on 2025-09-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomege', '0002_alter_customuser_age_alter_customuser_room_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bedtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='waketime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
