# Generated by Django 5.2.6 on 2025-09-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomege', '0003_alter_customuser_bedtime_alter_customuser_waketime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='church',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dishes_scenario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='late_hw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='relationship_expectation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='social_area',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
