# Generated by Django 5.2.6 on 2025-09-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomege', '0005_customuser_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['gender', 'grade', 'last_name', 'first_name', 'age'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dishes_scenario',
            field=models.TextField(blank=True, null=True, verbose_name="Dilemma: It's 1am.  You just finished eating and have several sirty dishes. You also have an 8am class tomorrow. What do you do?"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='late_hw',
            field=models.TextField(blank=True, null=True, verbose_name='How often and how late do you stay up doing home work?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='placed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='relationship_expectation',
            field=models.TextField(blank=True, null=True, verbose_name='What kind of relationship do you expect to have with your roomate? Explain.'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='room_state',
            field=models.IntegerField(blank=True, null=True, verbose_name='How clean your room right now? (on a scale of 1-10)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='social_area',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Do you like your living space to be a social area?'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
