# Generated by Django 5.2.6 on 2025-09-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomege', '0006_alter_customuser_city_and_more'),
        ('roomege', '0006_alter_customuser_options_customuser_gender_and_more'),
    ]

    operations = [
    ]
