# Generated by Django 5.2.6 on 2025-09-20 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomege', '0007_merge_20250920_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='match_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
