# Generated by Django 5.2.6 on 2025-09-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomege', '0008_customuser_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dishes_scenario',
            field=models.TextField(blank=True, null=True, verbose_name="Dilemma: It's 1am.  You just finished eating and have several dirty dishes. You also have an 8am class tomorrow. What do you do?"),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='room_state',
            field=models.IntegerField(blank=True, null=True, verbose_name='How clean is your room right now? (on a scale of 1-10)'),
        ),
    ]
